/** Canonical execution-contract validation for backend/problems/<slug>/. */
import loadProblemsFromFolders from "./lib/loadProblemsFromFolders.js";
import { generateDriverCode } from "../utils/generateDriverCode.js";
import { SUPPORTED_LANGUAGE_KEYS, REQUIRED_STARTER_LANGUAGE_KEYS } from "../config/languages.js";
const JAVA_RETURN_RE=/public\s+([\w<>[\],]+(?:\s*<[\w<>[\],\s]*>)?)\s+\w+\s*\(/;
const C_RETURN_RE=fn=>new RegExp(`^\\s*([\\w*]+(?:\\s+[\\w*]+)*)\\s+${fn}\\s*\\(`);
const CPP_RETURN_RE=fn=>new RegExp(`^\\s*([\\w:<>,]+(?:\\s+[\\w:<>,]+)*)\\s+${fn}\\s*\\(`);
function signatureReturnType(code,language,fn){if(!code||!fn)return null;if(language==='java')return code.match(JAVA_RETURN_RE)?.[1]?.trim()??null;const re=language==='c'?C_RETURN_RE(fn):CPP_RETURN_RE(fn);const line=code.split('\n').find(v=>re.test(v));return line?.match(re)?.[1]?.trim()??null;}
function validateProblem(p){const errors=[];if(!p.functionName?.trim())errors.push(`${p.slug}: missing functionName`);for(const language of SUPPORTED_LANGUAGE_KEYS){const code=p.starterCode?.[language];if(!code?.trim()){if(REQUIRED_STARTER_LANGUAGE_KEYS.includes(language))errors.push(`${p.slug}: starterCode.${language} missing/empty`);continue;}const declared=p.returnType?.[language];if(declared&&['java','cpp','c'].includes(language)){const actual=signatureReturnType(code,language,p.functionName);if(!actual)errors.push(`${p.slug}: could not read ${language} return type for ${p.functionName}`);else if(actual!==declared)errors.push(`${p.slug}: ${language} starter declares ${actual}, returnType says ${declared}`);}}if(!p.starterCode?.c?.trim())errors.push(`${p.slug}: starterCode.c missing/empty (C is production-enabled and must cover every canonical problem)`);if(!p.testcases?.length)errors.push(`${p.slug}: no visible testcases`);if(!p.hiddentestcases?.length)errors.push(`${p.slug}: no hidden testcases`);const testcase=p.testcases?.[0];if(testcase&&!p.operationSequence?.enabled)for(const language of ['java','cpp','c']){if(!p.starterCode?.[language])continue;try{const generated=generateDriverCode(language,p.starterCode[language],testcase.input,p.functionName,p.returnType?.[language],p.paramTypes?.[language]);if(/\bObject\s+\w+\s*=/.test(generated))errors.push(`${p.slug}: generated ${language} driver contains Object argument declaration`);}catch(error){errors.push(`${p.slug}: driver generation failed for ${language}: ${error.message}`);}}return errors;}
async function main(){const problems=await loadProblemsFromFolders();const errors=problems.flatMap(validateProblem);console.log(`Validated ${problems.length} canonical problem folder(s).`);if(errors.length){console.error(`Found ${errors.length} execution-contract error(s):`);errors.forEach(e=>console.error(`- ${e}`));process.exitCode=1;return;}console.log('All canonical problem execution contracts passed.');}
main().catch(error=>{console.error('Problem contract validation failed:',error);process.exitCode=1;});
