const esc=s=>String(s).replace(/\\/g,"\\\\").replace(/"/g,'\\"');
const listLit=a=>`{${a.map(Number).join(',')}}`;
const scalar=(k,v)=>typeof v==='string'?`char* ${k} = "${esc(v)}";`:typeof v==='boolean'?`bool ${k} = ${v?'true':'false'};`:`int ${k} = ${v};`;
const listHelper=`\n#ifndef CODECLUB_LISTNODE_DEFINED\n#define CODECLUB_LISTNODE_DEFINED\ntypedef struct ListNode { int val; struct ListNode* next; } ListNode;\n#endif\nstatic ListNode* cc_build_list(const int*v,int n){ListNode*h=NULL,*t=NULL;for(int i=0;i<n;i++){ListNode*x=malloc(sizeof(ListNode));x->val=v[i];x->next=NULL;if(!h)h=x;else t->next=x;t=x;}return h;}\nstatic void cc_print_list(ListNode*h){printf("[");int f=1;while(h){if(!f)printf(",");printf("%d",h->val);f=0;h=h->next;}printf("]\\n");}`;
const treeHelper=`\n#ifndef CODECLUB_TREENODE_DEFINED\n#define CODECLUB_TREENODE_DEFINED\ntypedef struct TreeNode { int val; struct TreeNode* left; struct TreeNode* right; } TreeNode;\n#endif\nstatic TreeNode* cc_tree_node(int v){TreeNode*n=malloc(sizeof(TreeNode));n->val=v;n->left=n->right=NULL;return n;}\nstatic TreeNode* cc_build_tree(const int*v,int n){if(n<=0||v[0]==INT_MIN)return NULL;TreeNode**a=calloc((size_t)n,sizeof(TreeNode*));for(int i=0;i<n;i++)if(v[i]!=INT_MIN)a[i]=cc_tree_node(v[i]);for(int i=0;i<n;i++)if(a[i]){int l=2*i+1,r=2*i+2;if(l<n)a[i]->left=a[l];if(r<n)a[i]->right=a[r];}TreeNode*r=a[0];free(a);return r;}\nstatic TreeNode* cc_find_value(TreeNode*r,int v){if(!r)return NULL;if(r->val==v)return r;TreeNode*x=cc_find_value(r->left,v);return x?x:cc_find_value(r->right,v);}\nstatic void cc_print_tree(TreeNode*r){if(!r){printf("[]\\n");return;}TreeNode*q[4096];int h=0,t=1;q[0]=r;printf("[");int f=1,last=1;while(h<t){TreeNode*n=q[h++];if(n){if(!f)printf(",");printf("%d",n->val);f=0;last=h;q[t++]=n->left;q[t++]=n->right;}else if(h<last){if(!f)printf(",null");}}printf("]\\n");}`;
const graphHelper=`\n#ifndef CODECLUB_GRAPHNODE_DEFINED\n#define CODECLUB_GRAPHNODE_DEFINED\ntypedef struct Node { int val; int numNeighbors; struct Node** neighbors; } Node;\n#endif\nstatic Node* cc_build_graph(int**a,int rows,int*c){if(rows<=0)return NULL;Node**n=calloc((size_t)rows,sizeof(Node*));for(int i=0;i<rows;i++){n[i]=calloc(1,sizeof(Node));n[i]->val=i+1;n[i]->numNeighbors=c[i];n[i]->neighbors=c[i]?calloc((size_t)c[i],sizeof(Node*)):NULL;}for(int i=0;i<rows;i++)for(int j=0;j<c[i];j++){int v=a[i][j]-1;n[i]->neighbors[j]=(v>=0&&v<rows)?n[v]:NULL;}Node*r=n[0];free(n);return r;}\nstatic void cc_print_graph(Node*r){if(!r){printf("[]\\n");return;}Node*q[1024],*seen[1024];int h=0,t=1,s=0;q[0]=r;while(h<t){Node*n=q[h++];seen[s++]=n;for(int i=0;i<n->numNeighbors&&t<1024;i++){Node*x=n->neighbors[i];int k=0;for(int j=0;j<s;j++)if(seen[j]==x)k=1;for(int j=0;j<t&&!k;j++)if(q[j]==x)k=1;if(!k)q[t++]=x;}}printf("[");for(int i=0;i<s;i++){if(i)printf(",");printf("[");for(int j=0;j<seen[i]->numNeighbors;j++){if(j)printf(",");printf("%d",seen[i]->neighbors[j]->val);}printf("]");}printf("]\\n");}`;
const listFns=new Set(['addTwoNumbers','getIntersectionNode','hasCycle','reorderList','reverseKGroup','mergeKLists','isPalindrome']);
const treeFns=new Set(['levelOrder','rightSideView','buildTree','kthSmallest','lowestCommonAncestor','widthOfBinaryTree','pathSum']);
const known=new Set([...listFns,...treeFns,'cloneGraph','accountsMerge','solveNQueens','partition','firstBadVersion','reverseBits','serialize']);
export function supports({language,returnType,paramTypes,fn}){return language==='c'&&(known.has(fn)||Object.values(paramTypes||{}).some(t=>/ListNode|TreeNode|GraphNode/.test(t))||/ListNode|TreeNode|char\*\*\*|uint32_t/.test(returnType||''));}
export function generate({language,userCode,fn,returnType,args}){
 if(!supports({language,returnType,paramTypes:{},fn}))return null;
 const inc=`#include <stdio.h>\n#include <stdlib.h>\n#include <stdbool.h>\n#include <stdint.h>\n#include <limits.h>\n#include <string.h>`;
 if(listFns.has(fn)){
   if(fn==='getIntersectionNode'){const a=args.find(x=>x.key==='listA')?.value||[],b=args.find(x=>x.key==='listB')?.value||[],sa=args.find(x=>x.key==='skipA')?.value??a.length,sb=args.find(x=>x.key==='skipB')?.value??b.length,iv=args.find(x=>x.key==='intersectVal')?.value||0;const av=a.slice(0,sa),bv=b.slice(0,sb),tail=iv?a.slice(sa):[];return `${inc}\n${listHelper}\n${userCode}\nint main(void){int _a[${Math.max(1,av.length)}]=${av.length?listLit(av):'{0}'};int _b[${Math.max(1,bv.length)}]=${bv.length?listLit(bv):'{0}'};int _t[${Math.max(1,tail.length)}]=${tail.length?listLit(tail):'{0}'};ListNode*headA=cc_build_list(_a,${av.length}),*headB=cc_build_list(_b,${bv.length});${tail.length?`ListNode*shared=cc_build_list(_t,${tail.length});ListNode*x=headA;if(x){while(x->next)x=x->next;x->next=shared;}else headA=shared;x=headB;if(x){while(x->next)x=x->next;x->next=shared;}else headB=shared;`:''}ListNode*r=${fn}(headA,headB);if(r)printf("%d\\n",r->val);else printf("null\\n");return 0;}\n`;}
   if(fn==='mergeKLists'){const rows=args.find(x=>x.key==='lists')?.value||[];const decl=rows.map((r,i)=>`int _l${i}[${Math.max(1,r.length)}]=${r.length?listLit(r):'{0}'};ListNode*_n${i}=cc_build_list(_l${i},${r.length});`).join('');const arr=rows.map((_,i)=>`_n${i}`).join(',');return `${inc}\n${listHelper}\n${userCode}\nint main(void){${decl}ListNode*_lists[${Math.max(1,rows.length)}]={${arr}};ListNode*r=${fn}(_lists,${rows.length});cc_print_list(r);return 0;}\n`;}
   const listArgs=args.filter(x=>Array.isArray(x.value));const key=listArgs[0]?.key||'head';const decl=listArgs.map(x=>{const vals=x.value;return `int _${x.key}Vals[${Math.max(1,vals.length)}]=${vals.length?listLit(vals):'{0}'};ListNode*${x.key}=cc_build_list(_${x.key}Vals,${vals.length});`;}).join('');const listKeys=new Set(listArgs.map(x=>x.key));const extras=args.filter(x=>!listKeys.has(x.key)).map(x=>scalar(x.key,x.value)).join('');const call=args.map(x=>x.key).join(',');let out;if(returnType==='ListNode*')out=`ListNode*r=${fn}(${call});cc_print_list(r);`;else if(returnType==='void')out=`${fn}(${call});cc_print_list(${key});`;else if(returnType==='bool')out=`bool r=${fn}(${call});printf(r?"true\\n":"false\\n");`;else out=`int r=${fn}(${call});printf("%d\\n",r);`;return `${inc}\n${listHelper}\n${userCode}\nint main(void){${decl}${extras}${out}return 0;}\n`;
 }
 if(treeFns.has(fn)){
   const root=args.find(x=>x.key==='root')?.value||[];
   if(fn==='buildTree'){const pre=args.find(x=>x.key==='preorder')?.value||[],ino=args.find(x=>x.key==='inorder')?.value||[];const pi=pre.length?listLit(pre):'{0}',ii=ino.length?listLit(ino):'{0}';return `${inc}\n${treeHelper}\n${userCode}\nint main(void){int preorder[${Math.max(1,pre.length)}]=${pi};int inorder[${Math.max(1,ino.length)}]=${ii};TreeNode*r=${fn}(preorder,${pre.length},inorder,${ino.length});cc_print_tree(r);return 0;}\n`;}
   const rv=root.map(v=>v==null?'INT_MIN':v).join(',')||'0';const decl=`int _root[${Math.max(1,root.length)}]={${rv}};TreeNode*root=cc_build_tree(_root,${root.length});`;let extras='';if(args.some(x=>x.key==='p'))extras+=`TreeNode*p=cc_find_value(root,${Number(args.find(x=>x.key==='p').value)});`;if(args.some(x=>x.key==='q'))extras+=`TreeNode*q=cc_find_value(root,${Number(args.find(x=>x.key==='q').value)});`;const scalarArgs=args.filter(x=>x.key!=='root'&&x.key!=='p'&&x.key!=='q');const scalarDecls=scalarArgs.map(x=>scalar(x.key,x.value)).join('');const call=['root',...args.filter(x=>x.key==='p'||x.key==='q').map(x=>x.key),...scalarArgs.map(x=>x.key)];let out;if(returnType==='TreeNode*')out=`TreeNode*r=${fn}(${call.join(',')});cc_print_tree(r);`;else if(returnType==='int*')out=`int rs=0;int*r=${fn}(${call.join(',')},&rs);printf("[");for(int i=0;i<rs;i++){if(i)printf(",");printf("%d",r[i]);}printf("]\\n");`;else if(returnType==='int**')out=`int rs=0;int*cs=NULL;int**r=${fn}(${call.join(',')},&rs,&cs);printf("[");for(int i=0;i<rs;i++){if(i)printf(",");printf("[");for(int j=0;j<cs[i];j++){if(j)printf(",");printf("%d",r[i][j]);}printf("]");}printf("]\\n");`;else out=`int r=${fn}(${call.join(',')});printf("%d\\n",r);`;return `${inc}\n${treeHelper}\n${userCode}\nint main(void){${decl}${extras}${scalarDecls}${out}return 0;}\n`;
 }
 if(fn==='cloneGraph'){const adj=args.find(x=>x.key==='adjList')?.value||[];const rows=adj.map((r,i)=>`int _a${i}[${Math.max(1,r.length)}]=${r.length?listLit(r):'{0}'};`).join('');const ptr=adj.map((_,i)=>`_a${i}`).join(',');const cols=adj.map(r=>r.length).join(',');return `${inc}\n${graphHelper}\n${userCode}\nint main(void){${rows}int*_adj[${Math.max(1,adj.length)}]={${ptr}};int _cols[${Math.max(1,adj.length)}]={${cols||'0'}};Node*node=cc_build_graph(_adj,${adj.length},_cols);Node*r=${fn}(node);cc_print_graph(r);return 0;}\n`;}
 if(fn==='accountsMerge'||fn==='solveNQueens'||fn==='partition'){const a=args.find(x=>x.key==='accounts')||args.find(x=>x.key==='n')||args.find(x=>x.key==='s');let decl='',call='';if(a?.key==='accounts'){const rows=a.value||[];rows.forEach((r,i)=>{decl+=`char*_r${i}[${Math.max(1,r.length)}]={${r.map(s=>`"${esc(s)}"`).join(',')}};`;});decl+=`char**accounts[${Math.max(1,rows.length)}]={${rows.map((_,i)=>`_r${i}`).join(',')}};int accountsSize=${rows.length};int accountsColSize[${Math.max(1,rows.length)}]={${rows.map(r=>r.length).join(',')||'0'}};`;call='accounts,accountsSize,accountsColSize';}else{decl=scalar(a.key,a.value);call=a.key;}return `${inc}\n${userCode}\nint main(void){${decl}int returnSize=0;int*returnColumnSizes=NULL;char***r=${fn}(${call},&returnSize,&returnColumnSizes);printf("[");for(int i=0;i<returnSize;i++){if(i)printf(",");printf("[");for(int j=0;j<returnColumnSizes[i];j++){if(j)printf(",");printf("\\\"%s\\\"",r[i][j]);}printf("]");}printf("]\\n");return 0;}\n`;}
 if(fn==='firstBadVersion'){const n=args.find(x=>x.key==='n')?.value||0,bad=args.find(x=>x.key==='bad')?.value||1;return `${inc}\nstatic int _cc_bad=${bad};static bool isBadVersion(int v){return v>=_cc_bad;}\n${userCode}\nint main(void){int r=${fn}(${n});printf("%d\\n",r);return 0;}\n`;}
 if(fn==='reverseBits'&&returnType==='uint32_t'){const n=args[0]?.value||0;return `${inc}\n${userCode}\nint main(void){uint32_t n=${n};uint32_t r=${fn}(n);printf("%u\\n",r);return 0;}\n`;}
 if(fn==='serialize'){const root=args.find(x=>x.key==='root')?.value||[],rv=root.map(v=>v==null?'INT_MIN':v).join(',')||'0';return `${inc}\n${treeHelper}\n${userCode}\nint main(void){int _root[${Math.max(1,root.length)}]={${rv}};TreeNode*root=cc_build_tree(_root,${root.length});char*encoded=${fn}(root);TreeNode*r=encoded?deserialize(encoded):NULL;cc_print_tree(r);return 0;}\n`;}
 return null;
}
