import * as cStructuredDriver from "./cStructuredDriver.js";

function hasListContract(paramTypes,returnType){const values=Object.values(paramTypes||{});return values.some(t=>/ListNode/.test(t))||/ListNode/.test(returnType||'');}
function jsArrayLiteral(values){return `{${values.map(v=>String(Number(v))).join(',')}}`;}
function javaListNodeType(){return `\nclass ListNode { int val; ListNode next; ListNode(int val){this.val=val;} }\n`;}
function javaListHelpers(){return `\nstatic ListNode buildList(int[] v){ListNode d=new ListNode(0),t=d;for(int x:v){t.next=new ListNode(x);t=t.next;}return d.next;}\nstatic String listToJson(ListNode h){StringBuilder o=new StringBuilder("[");boolean f=true;while(h!=null){if(!f)o.append(',');o.append(h.val);f=false;h=h.next;}return o.append(']').toString();}\n`;}
function cppListHelper(){return `\nstruct ListNode{int val;ListNode*next;ListNode(int x):val(x),next(nullptr){}};ListNode*buildList(const vector<int>&v){ListNode d(0),*t=&d;for(int x:v){t->next=new ListNode(x);t=t->next;}return d.next;}void printListJson(ListNode*h){cout<<"[";bool f=true;while(h){if(!f)cout<<",";cout<<h->val;f=false;h=h->next;}cout<<"]";}\n`;}
function cListHelper(){return `\ntypedef struct ListNode{int val;struct ListNode*next;}ListNode;ListNode*buildList(const int*v,int n){ListNode*h=NULL,*t=NULL;for(int i=0;i<n;i++){ListNode*x=malloc(sizeof(ListNode));x->val=v[i];x->next=NULL;if(!h)h=x;else t->next=x;t=x;}return h;}void printListJson(ListNode*h){printf("[");int f=1;while(h){if(!f)printf(",");printf("%d",h->val);f=0;h=h->next;}printf("]");}\n`;}
function isListType(t){return /ListNode/.test(t||'');}
export function supports({language,returnType,paramTypes,fn,args}){if(language==='c'&&cStructuredDriver.supports({language,returnType,paramTypes,fn,args}))return true;return hasListContract(paramTypes,returnType);}
export function generate({language,userCode,fn,returnType,args,paramTypes}){
 if(language==='c'&&cStructuredDriver.supports({language,returnType,paramTypes,fn,args}))return cStructuredDriver.generate({language,userCode,fn,returnType,args,paramTypes});
 if(!hasListContract(paramTypes,returnType))return null;const lists=args.filter(({key})=>isListType(paramTypes[key]));if(!lists.length&&!isListType(returnType))throw new Error('structured list driver: missing list contract');
 if(language==='java'){const d=lists.map(({key,value})=>`int[] ${key}Values=new int[] ${jsArrayLiteral(value)};ListNode ${key}=buildList(${key}Values);`).join('\n');const ca=args.map(x=>x.key).join(', ');const lr=returnType==='ListNode',vr=returnType==='void';const out=lr?`ListNode result=solution.${fn}(${ca});System.out.println(listToJson(result));`:vr?`solution.${fn}(${ca});System.out.println(listToJson(${lists[0]?.key}));`:`boolean result=solution.${fn}(${ca});System.out.println(result?"true":"false");`;return `import java.util.*;${javaListNodeType()}${userCode}class Main{${javaListHelpers()}public static void main(String[]a){try{${d}Solution solution=new Solution();${out}}catch(Exception e){System.out.println("RUNTIME_ERROR:"+e.getMessage());}}}`;}
 if(language==='cpp'){const d=lists.map(({key,value})=>`vector<int>${key}Values={${value.join(',')}};ListNode*${key}=buildList(${key}Values);`).join('\n');const ca=args.map(x=>x.key).join(', ');const lr=returnType==='ListNode*',vr=returnType==='void';const out=lr?`ListNode*result=solution.${fn}(${ca});printListJson(result);cout<<endl;`:vr?`solution.${fn}(${ca});printListJson(${lists[0]?.key});cout<<endl;`:`bool result=solution.${fn}(${ca});cout<<(result?"true":"false")<<endl;`;return `#include <bits/stdc++.h>\nusing namespace std;${cppListHelper()}${userCode}int main(){${d}Solution solution;${out}return 0;}`;}
 if(language==='c'){const d=lists.map(({key,value})=>`int ${key}Values[]=${jsArrayLiteral(value)};int ${key}Size=${value.length};struct ListNode*${key}=buildList(${key}Values,${key}Size);`).join('\n');const ca=args.map(x=>x.key).join(', ');const lr=returnType==='ListNode*',vr=returnType==='void';const out=lr?`ListNode*result=${fn}(${ca});printListJson(result);printf("\\n");`:vr?`${fn}(${ca});printListJson(${lists[0]?.key});printf("\\n");`:`bool result=${fn}(${ca});printf(result?"true\\n":"false\\n");`;return `#include <stdio.h>\n#include <stdlib.h>\n#include <stdbool.h>${cListHelper()}${userCode}int main(void){${d}${out}return 0;}`;}
 throw new Error(`structured list driver: unsupported language ${language}`);
}
