import * as cStructuredDriver from "./cStructuredDriver.js";

function hasListContract(paramTypes,returnType){const values=Object.values(paramTypes||{});return values.some(t=>/ListNode/.test(t))||/ListNode/.test(returnType||'');}
function jsArrayLiteral(values){return `{${values.map(v=>String(Number(v))).join(',')}}`;}
function javaListNodeType(){return `\nclass ListNode { int val; ListNode next; ListNode(int val){this.val=val;} }\n`;}
function javaListHelpers(){return `\nstatic ListNode buildList(int[] v){ListNode d=new ListNode(0),t=d;for(int x:v){t.next=new ListNode(x);t=t.next;}return d.next;}\nstatic String listToJson(ListNode h){StringBuilder o=new StringBuilder("[");boolean f=true;while(h!=null){if(!f)o.append(',');o.append(h.val);f=false;h=h.next;}return o.append(']').toString();}\n`;}
function cppListHelper(){return `\nstruct ListNode{int val;ListNode*next;ListNode(int x):val(x),next(nullptr){}};ListNode*buildList(const vector<int>&v){ListNode d(0),*t=&d;for(int x:v){t->next=new ListNode(x);t=t->next;}return d.next;}void printListJson(ListNode*h){cout<<"[";bool f=true;while(h){if(!f)cout<<",";cout<<h->val;f=false;h=h->next;}cout<<"]";}\n`;}
function isListType(t){return /ListNode/.test(t||'');}
export function supports({language,returnType,paramTypes,fn,args}){if(language==='c'&&cStructuredDriver.supports({language,returnType,paramTypes,fn,args}))return true;return hasListContract(paramTypes,returnType);}
export function generate({language,userCode,fn,returnType,args,paramTypes}){
 if(language==='c'&&cStructuredDriver.supports({language,returnType,paramTypes,fn,args}))return cStructuredDriver.generate({language,userCode,fn,returnType,args,paramTypes});
 if(!hasListContract(paramTypes,returnType))return null;const lists=args.filter(({key})=>isListType(paramTypes[key]));if(!lists.length&&!isListType(returnType))throw new Error('structured list driver: missing list contract');
 if(language==='java'){const d=lists.map(({key,value})=>`int[] ${key}Values = new int[] ${jsArrayLiteral(value)};\nListNode ${key} = buildList(${key}Values);`).join('\n');const ca=args.map(x=>x.key).join(', ');const lr=returnType==='ListNode',vr=returnType==='void';const out=lr?`ListNode result = solution.${fn}(${ca});\nSystem.out.println(listToJson(result));`:vr?`solution.${fn}(${ca});\nSystem.out.println(listToJson(${lists[0]?.key}));`:`boolean result = solution.${fn}(${ca});\nSystem.out.println(result ? "true" : "false");`;return `import java.util.*;${javaListNodeType()}${userCode}class Main{${javaListHelpers()}public static void main(String[]a){try{${d}\nSolution solution = new Solution();\n${out}}catch(Exception e){System.out.println("RUNTIME_ERROR:"+e.getMessage());}}}`;}
 if(language==='cpp'){const d=lists.map(({key,value})=>`vector<int> ${key}Values = {${value.join(',')}};\nListNode* ${key} = buildList(${key}Values);`).join('\n');const ca=args.map(x=>x.key).join(', ');const lr=returnType==='ListNode*',vr=returnType==='void';const out=lr?`ListNode* result = solution.${fn}(${ca});\nprintListJson(result); cout << endl;`:vr?`solution.${fn}(${ca});\nprintListJson(${lists[0]?.key}); cout << endl;`:`bool result = solution.${fn}(${ca});\ncout << (result ? "true" : "false") << endl;`;return `#include <bits/stdc++.h>\nusing namespace std;${cppListHelper()}${userCode}int main(){${d}\nSolution solution;\n${out}\nreturn 0;}`;}
 throw new Error(`structured list driver: unsupported language ${language}`);
}