/**
 * generateProblemFallback.js
 *
 * Generates the frontend's emergency problem catalog from the canonical
 * backend/problems/<slug>/ folders.
 *
 * IMPORTANT:
 * - backend/problems/ is the authoring source of truth.
 * - hidden-testcases.json is never read or emitted here.
 * - editorial.md is intentionally omitted because it is gated server-side.
 * - The generated module is ignored by git and recreated before dev/build/test.
 *
 * This keeps the API-down fallback resilient without keeping a second,
 * hand-authored copy of the problem catalog in src/data/problems.js.
 */

import fs from "fs/promises";
import path from "path";

const ROOT = process.cwd();
const PROBLEMS_DIR = path.join(ROOT, "backend", "problems");
const OUTPUT_DIR = path.join(ROOT, "src", "data", "generated");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "problemFallback.js");

const XP_BY_DIFFICULTY = {
  Easy: 10,
  Medium: 25,
  Hard: 50,
};

async function readJson(filePath) {
  return JSON.parse(await fs.readFile(filePath, "utf8"));
}

async function readOptionalJson(filePath, fallback) {
  try {
    return await readJson(filePath);
  } catch (error) {
    if (error.code === "ENOENT") return fallback;
    throw error;
  }
}

async function readStarterCode(folderPath) {
  const starterPath = path.join(folderPath, "starter");
  const entries = await fs.readdir(starterPath, { withFileTypes: true });
  const starterCode = {};

  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const extension = path.extname(entry.name);
    const key = path.basename(entry.name, extension);
    starterCode[key] = await fs.readFile(path.join(starterPath, entry.name), "utf8");
  }

  return starterCode;
}

async function loadPublicProblem(slug) {
  const folderPath = path.join(PROBLEMS_DIR, slug);
  const meta = await readJson(path.join(folderPath, "meta.json"));
  const description = await fs.readFile(path.join(folderPath, "description.md"), "utf8");
  const visibleTestCases = await readJson(path.join(folderPath, "testcases.json"));
  const hints = await readOptionalJson(path.join(folderPath, "hints.json"), []);
  const starterCode = await readStarterCode(folderPath);

  return {
    ...meta,
    description,
    visibleTestCases,
    testcases: visibleTestCases,
    starterCode,
    hints,
    xp: XP_BY_DIFFICULTY[meta.difficulty] ?? null,
  };
}

async function main() {
  const entries = await fs.readdir(PROBLEMS_DIR, { withFileTypes: true });
  const slugs = entries
    .filter((entry) => entry.isDirectory() && entry.name !== ".gitkeep")
    .map((entry) => entry.name)
    .sort();

  const problems = await Promise.all(slugs.map(loadPublicProblem));
  problems.sort((a, b) => (a.id ?? 0) - (b.id ?? 0));

  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  const output = [
    "// AUTO-GENERATED FILE — DO NOT EDIT.",
    "// Source: backend/problems/<slug>/ (canonical problem authoring source).",
    "// Regenerated by scripts/generateProblemFallback.js.",
    "// Hidden tests and editorial content are intentionally excluded.",
    `export default ${JSON.stringify(problems, null, 2)};`,
    "",
  ].join("\n");

  await fs.writeFile(OUTPUT_FILE, output, "utf8");
  console.log(`Generated public problem fallback: ${problems.length} problem(s).`);
  console.log(`Output: ${path.relative(ROOT, OUTPUT_FILE)}`);
}

main().catch((error) => {
  console.error("[generateProblemFallback] Failed:", error);
  process.exitCode = 1;
});
